@uriAuth = http://localhost:8000/api/auth

PATCH {{uriAuth}}
Content-Type: application/json

{
  "idUsuario": "2",
  "passw": "2"
}

###

DELETE {{uriAuth}}/2

###




###

@uriCliente = http://localhost:8000/api/cliente
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3NDkwNTY3MTMsImV4cCI6MTc0OTA1Njc1OCwic3ViIjoiMiIsInJvbCI6IjQiLCJub20iOiJKb3NlIn0.K7M8qrvI-a_-Zpb7itc7nWoCUBuejJ4AttsO6cbdjUU

GET {{uriCliente}}/read
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{uriCliente}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "idCliente": 8,
  "nombre": "sda",
  "apellido1": "asda",
  "apellido2": "asd",
  "telefono": "556789",
  "celular": "654845",
  "direccion": "Avenida Central 101",
  "correo": "sad.asda@example.com"
}

###